#!/bin/bash 
date
export PS4=' $SECONDS + '
set -x

####################################
# obtain unique process id (pid) and make temp directory
####################################
export jobid=${jobid:-$job.o$$}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA
export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################
#export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}
export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-ens_tracker}
export RUN=${RUN:-gdas}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${NWROOT:?}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-$HOMEens_tracker/exec}
export FIXens_tracker=${FIXens_tracker:-$HOMEens_tracker/fix}
export USHens_tracker=${USHens_tracker:-$HOMEens_tracker/ush}
export SCRIPTens_tracker=${SCRIPTens_tracker:-$HOMEens_tracker/scripts}

##############################
# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
#. PDY
export PDY=20230413

##############################################
# Define COM directories
##############################################
#mac=`echo ${SITE}`
#mac2=$(hostname | cut -c1-2)

if [[ -d /scratch2 ]] ; then
  # We are on NOAA HERA
#  export COMINgfs=${COMINgfs:-${COMROOTp1}/gfs/prod/gfs.${PDY}}
#  export COMINgdas=${COMINgdas:-${COMROOTp1}/gfs/prod/gdas.${PDY}}
#  export COMINgdas=/scratch2/NCEPDEV/stmp3/Jiayi.Peng/data_4_gdas
#  export COMINsyn=${COMINsyn:-${COMROOTp1}/arch/prod/syndat}
#  export COMINsyn=/scratch1/NCEPDEV/hwrf/noscrub/input/SYNDAT
  export COMINsyn=/scratch2/NCEPDEV/ensemble/Jiayi.Peng/noscrub/MetTCData/TCvital
  export COMINgfs=/scratch2/NCEPDEV/ensemble/Jiayi.Peng/noscrub/ptmp/gfs.${PDY}
  export COMINgdas=/scratch2/NCEPDEV/ensemble/Jiayi.Peng/noscrub/ptmp/gdas.${PDY}

elif [[ -d /work ]] ; then
  # We are on MSU Orion
#  export COMINgfs=${COMINgfs:-${COMROOTp1}/gfs/prod/gfs.${PDY}}
#  export COMINgfs=/work/noaa/stmp/Jiayi.Peng/data_4_gfs
#  export COMINgdas=/work/noaa/stmp/Jiayi.Peng/data_4_gdas
#  export COMINsyn=${COMINsyn:-${COMROOTp1}/arch/prod/syndat}
#  export COMINsyn=/work/noaa/global/kfriedma/glopara/git/tracker/syndat
  export COMINsyn=/work/noaa/global/Jiayi.Peng/syndat
  export COMINgfs=/work/noaa/global/Jiayi.Peng/ptmp/gfs.${PDY}
  export COMINgdas=/work/noaa/global/Jiayi.Peng/ptmp/gdas.${PDY}

elif [[ -d /lfs4/HFIP ]] ; then
  # We are on NOAA Jet
#  export COMINgfs=${COMINgfs:-${COMROOTp1}/gfs/prod/gfs.${PDY}}
#  export COMINgdas=${COMINgdas:-${COMROOTp1}/gfs/prod/gdas.${PDY}}
#  export COMINgdas=/scratch4/NCEPDEV/stmp3/Jiayi.Peng/gdas.20180522
#  export COMINsyn=${COMINsyn:-${COMROOTp1}/arch/prod/syndat}
  export COMINgfs=${COMINgfs:-/mnt/lfs4/HFIP/hwrfv3/Jiayi.Peng/data/gfs.20230222}
  export COMINgdas=${COMINgdas:-/mnt/lfs4/HFIP/hwrfv3/Jiayi.Peng/data/gdas.${PDY}}
  export COMINsyn=${COMINsyn:-/mnt/lfs4/HFIP/hwrf-data/hwrf-input/SYNDAT}

elif [[ -d /lfs/h1 ]] ; then  
  # We are on NOAA wcoss2	
#export COMINgfs=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})/gfs.${PDY}}
#export COMINsyn=${COMINsyn:-$(compath.py $envir/com/gfs/${gfs_ver})/syndat)}
#export COMINgdas=${COMINgdas:-$(compath.py $envir/com/gfs/${gfs_ver})/gdas.${PDY}}
  export COMINgfs=/lfs/h1/ops/prod/com/gfs/v16.3/gfs.$PDY
  export COMINsyn=/lfs/h1/ops/prod/com/gfs/v16.3/syndat
  export COMINgdas=/lfs/h1/ops/prod/com/gfs/v16.3/gdas.$PDY

else
  echo Job failed: unknown platform 1>&2
  err_exit "FAILED ${jobid} - ERROR IN unknown platform - ABNORMAL EXIT"

fi

export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${ens_tracker_ver}/${RUN}.${PDY}/${cyc}/tctrack}
export COMOUThur=${COMOUThur:-${COMROOT:?}/${NET}/${ens_tracker_ver}/global}
export COMOUTatcf=${COMOUTatcf:-${COMROOT:?}/${NET}/${ens_tracker_ver}/atcf}
mkdir -m 775 -p $COMOUT $COMOUThur $COMOUTatcf

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#############################################################
${SCRIPTens_tracker}/exgdas_tc_track.sh

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  rm -rf $DATA
fi

date
