#!/bin/sh 
date
export PS4=' $SECONDS + '
set -x

####################################
# obtain unique process id (pid) and make temp directory
####################################
export jobid=${jobid:-$job.o$$}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA
export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################
mkdir -p ${COMROOT}/logs/jlogfiles
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-ens_tracker}
export RUN=${RUN:-gfs}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${NWROOT:?}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-$HOMEens_tracker/exec}
export FIXens_tracker=${FIXens_tracker:-$HOMEens_tracker/fix}
export USHens_tracker=${USHens_tracker:-$HOMEens_tracker/ush}
export SCRIPTens_tracker=${SCRIPTens_tracker:-$HOMEens_tracker/scripts}

##############################
# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
#. PDY
export PDY=20210824

##############################################
# Define COM directories
##############################################
#mac=`echo ${SITE}`
#mac2=$(hostname | cut -c1-2)

if [[ -d /gpfs/hps && -e /etc/SuSE-release ]] ; then
  # We are on NOAA Luna or Surge
  export COMINgfs=${COMINgfs:-$(compath.py gfs/prod/gfs.$PDY)}
  export COMINsyn=${COMINsyn:-$(compath.py gfs/prod/syndat)}

elif [[ -L /usrx && "$( readlink /usrx 2> /dev/null )" =~ dell ]] ; then
  # We are on NOAA Mars or Venus
  export COMINgfs=${COMINgfs:-$(compath.py gfs/prod/gfs.$PDY)}
  export COMINsyn=${COMINsyn:-$(compath.py gfs/prod/syndat)}

elif [[ -d /scratch2 ]] ; then
  # We are on NOAA Hera
  export COMINgfs=${COMINgfs:-${COMROOTp1}/gfs/prod/gfs.${PDY}}
#  export COMINgfs=/scratch2/NCEPDEV/ensemble/Jiayi.Peng/noscrub/data_4_gfs
#  export COMINsyn=${COMINsyn:-${COMROOTp1}/arch/prod/syndat}
  export COMINsyn=/scratch1/NCEPDEV/hwrf/noscrub/input/SYNDAT

elif [[ -d /work ]] ; then
  # We are on MSU Orion
#  export COMINgfs=${COMINgfs:-${COMROOTp1}/gfs/prod/gfs.${PDY}}
  export COMINgfs=/work/noaa/stmp/Jiayi.Peng/data_4_gfs
#  export COMINsyn=${COMINsyn:-${COMROOTp1}/arch/prod/syndat}
#  export COMINsyn=/work/noaa/global/kfriedma/glopara/git/tracker/syndat
  export COMINsyn=/work/noaa/global/Jiayi.Peng/syndat

elif [[ -d /lfs3 ]] ; then
  # We are on NOAA Jet
#  export COMINgfs=${COMINgfs:-${COMROOTp1}/gfs/prod/gfs.${PDY}}
#  export COMINsyn=${COMINsyn:-${COMROOTp1}/arch/prod/syndat}
#  export COMINgfs=${COMINgfs:-/mnt/lfs3/projects/hwrfv3/Jiayi.Peng/data/gfs.${PDY}}
  export COMINsyn=${COMINsyn:-/mnt/lfs4/HFIP/hwrf-data/hwrf-input/SYNDAT}
  export COMINgfs=${COMINgfs:-/mnt/lfs4/HFIP/hwrfv3/Jiayi.Peng/data/gfs.20200612}
elif [[ -d /lfs/h1 ]] ; then
  # We are on NOAA wcoss2
#export COMINgfs=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})/gfs.${PDY}}
#export COMINsyn=${COMINsyn:-$(compath.py $envir/com/gfs/${gfs_ver})/syndat)}
  export COMINgfs=/lfs/h1/ops/canned/com/gfs/v16.2/gfs.$PDY
  export COMINsyn=/lfs/h1/ops/canned/com/gfs/v16.2/syndat  

else
  echo Job failed: unknown platform 1>&2
  err_exit "FAILED ${jobid} - ERROR IN unknown platform - ABNORMAL EXIT"
fi

export COMROOTp1=${COMROOT}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}/${cyc}/tctrack}
export COMOUThur=${COMOUThur:-${COMROOTp1:?}/hur/${envir}/global}
export COMOUTatcf=${COMOUTatcf:-${COMROOTp1:?}/nhc/${envir}/atcf}
mkdir -m 775 -p $COMOUT $COMOUThur $COMOUTatcf

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#############################################################
${SCRIPTens_tracker}/exgfs_tc_track.sh
export err=$?; err_chk

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  rm -rf $DATA
fi

date
