#!/bin/bash 
date
export PS4=' $SECONDS + '
set -x

####################################
# obtain unique process id (pid) and make temp directory
####################################
export jobid=${jobid:-$job.o$$}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-ens_tracker}
export RUN=${RUN:-gfs}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT:?}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-$HOMEens_tracker/exec}
export FIXens_tracker=${FIXens_tracker:-$HOMEens_tracker/fix}
export USHens_tracker=${USHens_tracker:-$HOMEens_tracker/ush}
export SCRIPTens_tracker=${SCRIPTens_tracker:-$HOMEens_tracker/scripts}

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY
##############################################
# Define COM directories
##############################################

if [[ -d /scratch2 ]] ; then
  # We are on NOAA Hera
  export COMINsyn=${COMINsyn:-/scratch2/NCEPDEV/ovp/Hana.Jafary/Input/TCvital}
  export COMINgfs=${COMINgfs:-/scratch2/NCEPDEV/ovp/Hana.Jafary/Input/gfs.${PDY}}

elif [[ -d /work2/noaa ]] ; then
  # We are on MSU Orion
  export COMINsyn=${COMINsyn:-/work2/noaa/hurricane/noscrub/hjafary/Input/TCvital}
  export COMINgfs=${COMINgfs:-/work2/noaa/hurricane/noscrub/hjafary/Input/gfs.${PDY}}

elif [[ -d /lfs5/HFIP ]] ; then
  # We are on NOAA Jet
  export COMINsyn=${COMINsyn:-/mnt/lfs5/HFIP/hwrfv3/Hananeh.Jafary/TCvital}
  export COMINgfs=${COMINgfs:-/mnt/lfs5/HFIP/hwrfv3/Hananeh.Jafary/gfs_data/gfs.${PDY}}

elif [[ -d /lfs/h1 ]] ; then
  # We are on NOAA wcoss2 
  export COMINgfs=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})/gfs.${PDY}}
  export COMINsyn=${COMINsyn:-$(compath.py $envir/com/gfs/${gfs_ver})/syndat)}

elif [[ -d /gpfs/f6 ]] ; then
  # We are on NOAA gaeac6
  export COMINsyn=${COMINsyn:-/gpfs/f6/drsa-hurr1/world-shared/noscrub/Hananeh.Jafary/gfs.${PDY}/TCvital}
  export COMINgfs=${COMINgfs:-/gpfs/f6/drsa-hurr1/world-shared/noscrub/Hananeh.Jafary/gfs.${PDY}}

else
  echo Job failed: unknown platform 1>&2
  err_exit "FAILED ${jobid} - ERROR IN unknown platform - ABNORMAL EXIT"
fi

export JYYYY=`echo ${PDY} | cut -c1-4`
export COMIN=${COMIN:-${COMROOT:?}/gfs.${PDY}/00/products/atmos/cyclone/genesis}
export COMINgenvit=${COMINgenvit:-${COMROOT:?}/gfs.${PDY}/00/products/atmos/cyclone/genesis_vital/}

export COMOUT=${COMOUT:-${COMROOT:?}/gfs.${PDY}/00/products/atmos/cyclone/genesis}
export COMOUTgenvit=${COMOUTgenvit:-${COMROOT:?}/gfs.${PDY}/00/products/atmos/cyclone/genesis_vital/}
mkdir -m 775 -p $COMOUT $COMOUTgenvit

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#############################################################
${SCRIPTens_tracker}/exgfs_tc_genesis.sh
export err=$?; err_chk

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  rm -rf $DATA
fi

date
